kind: Deployment
apiVersion: apps/v1
metadata:
  name: trivy-demo
  namespace: trivy-demo
  labels:
    app: trivy-demo
    app.kubernetes.io/part-of: trivy-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-demo
      deployment: trivy-demo
  template:
    metadata:
      labels:
        app: trivy-demo
        deployment: trivy-demo
    spec:
      containers:
        - name: trivy-demo
          image: quay.io/mooyeg/trivy-example
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APP_MODULE
              value: "trivy_app_sample:app"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
